// Code generated by snek; DO NOT EDIT.
package cmd

import (
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

var searchCmd = &cobra.Command{
	Use:     "search",
	Aliases: []string{"s"},
	Short:   "search google books",
	Long:    "search the google books api",
	Run:     searchCmdRun,
}

func init() {
	rootCmd.AddCommand(searchCmd)
}
